### ISSUE TITLE
Improper Licensing

### ISSUE THREAD

**Issue by HenrySlawniak** [MCME/Perks#6]
You really should not license other people's code without their consent.

Specifically, https://github.com/MCME/Perks/blob/master/src/main/java/com/mcmiddleearth/perks/listeners/GrapplingHookListener.java

I have a lot of issues with this being under the MIT, and the fact that it has been repackaged then relicensed.

**Comment by DonoA** [comment]
Being that you are an author of that file I acknowledge your claim. The rest has been cleared with dags. What license would you like on your file?

**Comment by HenrySlawniak** [comment]
Considering that you took it upon yourself to license my code, I would like you to remove it from this project.

**Comment by DonoA** [comment]
resolved by #7
